SymEdit\Bundle\AnalyticsBundle\Model\Visit:
    table: visit
    type: mappedSuperclass
    indexes:
        class_index:
            columns: [class]
        identifier_index:
            columns: [identifier]
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        class:
            type: string
            length: 255
            nullable: true
        identifier:
            type: integer
        visitDate:
            type: datetime
